name = "bolt-diy"
pages_build_output_dir = "build/client"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install pnpm && pnpm install && pnpm run build"

[[pages.functions]]
directory = "functions"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]